const ActionType = {
  SET_ERROR_ACTION: 'SET_ERROR_ACTION',
  SET_ID_ACTION: 'SET_ID_ACTION',
  SET_STATUS_ACTION: 'SET_STATUS_ACTION',
  SHORTEN_ACTION: 'SHORTEN_ACTION'
};

export default ActionType;
